os: linux

language: node_js

node_js: "8.11.2"

# Safelist
branches:
  only:
    - master

cache:
  npm: true
  pip: true

cache:
  npm: true
  pip: true

jobs:
  include:
    - before_script:
        - npm i
        - cd ./demo/ && npm i && cd ../
      script:
        - npm run test:eslint
        - npm run build
        - cd ./demo/ && npm run build && cd ../
